In [6]:
import pandas as pd
import requests
import pycountry
from bs4 import BeautifulSoup

In [11]:
soup = BeautifulSoup(requests.get('https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en').text, 'lxml')

In [72]:
countries = {'Afghanistan': 'AFG'}

In [73]:
base_url = 'https://apps.who.int/gho/data/'
for a in soup.select('ul.list_dash li a'):
    print(a.text)
    url = base_url + a['href']
    soup2 = BeautifulSoup(requests.get(url).text, 'lxml')
    for iframe in soup2.find_all('iframe'):
        src = iframe['src']
        break
    countries[a.text] = src.split(':')[-1]
countries

Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia (Plurinational State of)
Bosnia and Herzegovina
Botswana
Brazil
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo
Cook Islands
Costa Rica
Côte d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Democratic People's Republic of Korea
Democratic Republic of the Congo
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hungary
Iceland
India
Indonesia
Iran (Islamic Republic of)
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Lao People's Democratic Republic
Latvia
Lebanon
Lesotho
Liberia
Libya
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia (Federated States of)
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
New Zealand
Niue
Netherlands
Nicaragua
Niger
Nigeria
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Republic of Korea
Republic of Moldova
Romania
Russian Federation
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Suriname
Swaziland
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Thailand
The former Yugoslav Republic of Macedonia
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Republic of Tanzania
United Kingdom
United States of America
Uruguay
Uzbekistan
Vanuatu
Venezuela (Bolivarian Republic of)
Viet Nam
Yemen
Zambia
Zimbabwe

{'Afghanistan': 'AFG',
 'Albania': 'ALB',
 'Algeria': 'DZA',
 'Andorra': 'AND',
 'Angola': 'AGO',
 'Antigua and Barbuda': 'ATG',
 'Argentina': 'ARG',
 'Armenia': 'ARM',
 'Australia': 'AUS',
 'Austria': 'AUT',
 'Azerbaijan': 'AZE',
 'Bahamas': 'BHS',
 'Bahrain': 'BHR',
 'Bangladesh': 'BGD',
 'Barbados': 'BRB',
 'Belarus': 'BLR',
 'Belgium': 'BEL',
 'Belize': 'BLZ',
 'Benin': 'BEN',
 'Bhutan': 'BTN',
 'Bolivia (Plurinational State of)': 'BOL',
 'Bosnia and Herzegovina': 'BIH',
 'Botswana': 'BWA',
 'Brazil': 'BRA',
 'Brunei Darussalam': 'BRN',
 'Bulgaria': 'BGR',
 'Burkina Faso': 'BFA',
 'Burundi': 'BDI',
 'Cabo Verde': 'CPV',
 'Cambodia': 'KHM',
 'Cameroon': 'CMR',
 'Canada': 'CAN',
 'Central African Republic': 'CAF',
 'Chad': 'TCD',
 'Chile': 'CHL',
 'China': 'CHN',
 'Colombia': 'COL',
 'Comoros': 'COM',
 'Congo': 'COG',
 'Cook Islands': 'COK',
 'Costa Rica': 'CRI',
 'Croatia': 'HRV',
 'Cuba': 'CUB',
 'Cyprus': 'CYP',
 'Czechia': 'CZE',
 "Côte d'Ivoire": 'CIV',
 "Democratic People's Republic of Korea": 'PRK',
 'Democratic Republic of the Congo': 'COD',
 'Denmark': 'DNK',
 'Djibouti': 'DJI',
 'Dominica': 'DMA',
 'Dominican Republic': 'DOM',
 'Ecuador': 'ECU',
 'Egypt': 'EGY',
 'El Salvador': 'SLV',
 'Equatorial Guinea': 'GNQ',
 'Eritrea': 'ERI',
 'Estonia': 'EST',
 'Ethiopia': 'ETH',
 'Fiji': 'FJI',
 'Finland': 'FIN',
 'France': 'FRA',
 'Gabon': 'GAB',
 'Gambia': 'GMB',
 'Georgia': 'GEO',
 'Germany': 'DEU',
 'Ghana': 'GHA',
 'Greece': 'GRC',
 'Grenada': 'GRD',
 'Guatemala': 'GTM',
 'Guinea': 'GIN',
 'Guinea-Bissau': 'GNB',
 'Guyana': 'GUY',
 'Haiti': 'HTI',
 'Honduras': 'HND',
 'Hungary': 'HUN',
 'Iceland': 'ISL',
 'India': 'IND',
 'Indonesia': 'IDN',
 'Iran (Islamic Republic of)': 'IRN',
 'Iraq': 'IRQ',
 'Ireland': 'IRL',
 'Israel': 'ISR',
 'Italy': 'ITA',
 'Jamaica': 'JAM',
 'Japan': 'JPN',
 'Jordan': 'JOR',
 'Kazakhstan': 'KAZ',
 'Kenya': 'KEN',
 'Kiribati': 'KIR',
 'Kuwait': 'KWT',
 'Kyrgyzstan': 'KGZ',
 "Lao People's Democratic Republic": 'LAO',
 'Latvia': 'LVA',
 'Lebanon': 'LBN',
 'Lesotho': 'LSO',
 'Liberia': 'LBR',
 'Libya': 'LBY',
 'Lithuania': 'LTU',
 'Luxembourg': 'LUX',
 'Madagascar': 'MDG',
 'Malawi': 'MWI',
 'Malaysia': 'MYS',
 'Maldives': 'MDV',
 'Mali': 'MLI',
 'Malta': 'MLT',
 'Marshall Islands': 'MHL',
 'Mauritania': 'MRT',
 'Mauritius': 'MUS',
 'Mexico': 'MEX',
 'Micronesia (Federated States of)': 'FSM',
 'Monaco': 'MCO',
 'Mongolia': 'MNG',
 'Montenegro': 'MNE',
 'Morocco': 'MAR',
 'Mozambique': 'MOZ',
 'Myanmar': 'MMR',
 'Namibia': 'NAM',
 'Nauru': 'NRU',
 'Nepal': 'NPL',
 'Netherlands': 'NLD',
 'New Zealand': 'NZL',
 'Nicaragua': 'NIC',
 'Niger': 'NER',
 'Nigeria': 'NGA',
 'Niue': 'NIU',
 'Norway': 'NOR',
 'Oman': 'OMN',
 'Pakistan': 'PAK',
 'Palau': 'PLW',
 'Panama': 'PAN',
 'Papua New Guinea': 'PNG',
 'Paraguay': 'PRY',
 'Peru': 'PER',
 'Philippines': 'PHL',
 'Poland': 'POL',
 'Portugal': 'PRT',
 'Qatar': 'QAT',
 'Republic of Korea': 'KOR',
 'Republic of Moldova': 'MDA',
 'Romania': 'ROU',
 'Russian Federation': 'RUS',
 'Rwanda': 'RWA',
 'Saint Kitts and Nevis': 'KNA',
 'Saint Lucia': 'LCA',
 'Saint Vincent and the Grenadines': 'VCT',
 'Samoa': 'WSM',
 'San Marino': 'SMR',
 'Sao Tome and Principe': 'STP',
 'Saudi Arabia': 'SAU',
 'Senegal': 'SEN',
 'Serbia': 'SRB',
 'Seychelles': 'SYC',
 'Sierra Leone': 'SLE',
 'Singapore': 'SGP',
 'Slovakia': 'SVK',
 'Slovenia': 'SVN',
 'Solomon Islands': 'SLB',
 'Somalia': 'SOM',
 'South Africa': 'ZAF',
 'South Sudan': 'SSD',
 'Spain': 'ESP',
 'Sri Lanka': 'LKA',
 'Sudan': 'SDN',
 'Suriname': 'SUR',
 'Swaziland': 'SWZ',
 'Sweden': 'SWE',
 'Switzerland': 'CHE',
 'Syrian Arab Republic': 'SYR',
 'Tajikistan': 'TJK',
 'Thailand': 'THA',
 'The former Yugoslav Republic of Macedonia': 'MKD',
 'Timor-Leste': 'TLS',
 'Togo': 'TGO',
 'Tonga': 'TON',
 'Trinidad and Tobago': 'TTO',
 'Tunisia': 'TUN',
 'Turkey': 'TUR',
 'Turkmenistan': 'TKM',
 'Tuvalu': 'TUV',
 'Uganda': 'UGA',
 'Ukraine': 'UKR',
 'United Arab Emirates': 'ARE',
 'United Kingdom': 'GBR',
 'United Republic of Tanzania': 'TZA',
 'United States of America': 'USA',
 'Uruguay': 'URY',
 'Uzbekistan': 'UZB',
 'Vanuatu': 'VUT',
 'Venezuela (Bolivarian Republic of)': 'VEN',
 'Viet Nam': 'VNM',
 'Yemen': 'YEM',
 'Zambia': 'ZMB',
 'Zimbabwe': 'ZWE'}

In [ ]:
from io import StringIO

adf = pd.DataFrame()

In [90]:
skip = True
for c in countries:
    print(c)
    if c == 'Romania':
        skip = False
        print(countries[c])
    if skip:
        continue
    url = 'https://apps.who.int/gho/athena/data/data-verbose.csv?target=GHO/LIFE_0000000029,LIFE_0000000030,LIFE_0000000031,LIFE_0000000032,LIFE_0000000033,LIFE_0000000034,LIFE_0000000035&profile=verbose&filter=COUNTRY:%s' % countries[c]
    r = requests.get(url)
    if r.status_code == 200:
        try:
            df = pd.read_csv(StringIO(r.text))
            adf = adf.append(df)
        except Exception as e:
            print(e)
    else:
        print('Error %s' % c)

Serbia
Yemen
Eritrea
Malaysia
Niger
Dominican Republic
Austria
Georgia
Togo
Republic of Korea
Uruguay
Angola
Algeria
Qatar
Sri Lanka
Grenada
Djibouti
Tunisia
Saint Lucia
Swaziland
France
Marshall Islands
Costa Rica
Guinea
Equatorial Guinea
Indonesia
Guinea-Bissau
Hungary
Botswana
Lithuania
Benin
Antigua and Barbuda
Pakistan
Netherlands
Tajikistan
Syrian Arab Republic
Monaco
Cambodia
Germany
Viet Nam
United Arab Emirates
South Africa
El Salvador
Turkmenistan
Mauritius
Rwanda
Bosnia and Herzegovina
Micronesia (Federated States of)
Chile
Armenia
Saudi Arabia
Democratic Republic of the Congo
Italy
Senegal
The former Yugoslav Republic of Macedonia
Lesotho
Burkina Faso
Mali
Guyana
Maldives
Namibia
Central African Republic
Uganda
Morocco
Romania
ROU
No columns to parse from file
Russian Federation

/opt/venv3/lib/python3.5/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

Brunei Darussalam
South Sudan
Suriname
Cuba
Guatemala
Turkey
Sudan
Mozambique
Afghanistan
Ecuador
Samoa
China
Iceland
Ukraine
Republic of Moldova
Mauritania
Czechia
Jordan
Saint Kitts and Nevis
Bahamas
Norway
Denmark
Albania
Nauru
Nepal
India
Malawi
Côte d'Ivoire
Jamaica
Azerbaijan
Oman
Haiti
Canada
Nigeria
Cook Islands
Uzbekistan
Peru
Kuwait
Tonga
Vanuatu
Japan
Gambia
Bulgaria
Myanmar
United Republic of Tanzania
Slovakia
Slovenia
Nicaragua
Greece
Mongolia
Montenegro
Gabon
Croatia
Belgium
No columns to parse from file
New Zealand
Dominica
Seychelles
Egypt
Thailand
San Marino
Israel
Estonia
Ghana
Burundi
Congo
Papua New Guinea
Trinidad and Tobago
Cameroon
Belize
Portugal
Luxembourg
Ethiopia
Sierra Leone
Mexico
Ireland
Zambia
Honduras
United Kingdom
Libya
Zimbabwe
Saint Vincent and the Grenadines
Kiribati
Kyrgyzstan
Finland
Venezuela (Bolivarian Republic of)
Poland
Democratic People's Republic of Korea
Kazakhstan
Madagascar
Solomon Islands
Panama
Niue
United States of America
Fiji
Chad
Brazil
Sweden
Tuvalu
Liberia
Colombia
Barbados
Palau
Belarus
Spain
Malta
Timor-Leste
Argentina
Bolivia (Plurinational State of)
Australia
Philippines
Switzerland
Bahrain
Andorra
Bangladesh
Singapore
Somalia
Lebanon
Sao Tome and Principe
Bhutan
Comoros
Lao People's Democratic Republic
Iraq
Iran (Islamic Republic of)
Kenya
Paraguay
Cabo Verde
Cyprus
Latvia

In [91]:
adf

,AGEGROUP (CODE),AGEGROUP (DISPLAY),AGEGROUP (URL),COUNTRY (CODE),COUNTRY (DISPLAY),COUNTRY (URL),Comments,Display Value,GHO (CODE),GHO (DISPLAY),...,REGION (DISPLAY),REGION (URL),SEX (CODE),SEX (DISPLAY),SEX (URL),StdDev,StdErr,YEAR (CODE),YEAR (DISPLAY),YEAR (URL)
0,AGELT1,<1 year,NaN,SRB,Serbia,NaN,NaN,0.012,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
1,AGELT1,<1 year,NaN,SRB,Serbia,NaN,NaN,0.012,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
2,AGE5-9,5-9 years,NaN,SRB,Serbia,NaN,NaN,0.001,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
3,AGE5-9,5-9 years,NaN,SRB,Serbia,NaN,NaN,98618.520,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
4,AGE5-9,5-9 years,NaN,SRB,Serbia,NaN,NaN,88.314,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
5,AGE5-9,5-9 years,NaN,SRB,Serbia,NaN,NaN,492871.800,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
6,AGE15-19,15-19 years,NaN,SRB,Serbia,NaN,NaN,491413.200,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
7,AGE15-19,15-19 years,NaN,SRB,Serbia,NaN,NaN,5502668.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
8,AGE15-19,15-19 years,NaN,SRB,Serbia,NaN,NaN,55.900,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
9,AGE20-24,20-24 years,NaN,SRB,Serbia,NaN,NaN,0.001,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
10,AGE25-29,25-29 years,NaN,SRB,Serbia,NaN,NaN,46.300,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
11,AGE30-34,30-34 years,NaN,SRB,Serbia,NaN,NaN,0.001,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
12,AGE30-34,30-34 years,NaN,SRB,Serbia,NaN,NaN,0.006,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
13,AGE30-34,30-34 years,NaN,SRB,Serbia,NaN,NaN,97196.450,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
14,AGE30-34,30-34 years,NaN,SRB,Serbia,NaN,NaN,593.732,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
15,AGE40-44,40-44 years,NaN,SRB,Serbia,NaN,NaN,95668.200,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
16,AGE40-44,40-44 years,NaN,SRB,Serbia,NaN,NaN,1694.850,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
17,AGE40-44,40-44 years,NaN,SRB,Serbia,NaN,NaN,474456.200,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
18,AGE40-44,40-44 years,NaN,SRB,Serbia,NaN,NaN,3069173.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
19,AGE50-54,50-54 years,NaN,SRB,Serbia,NaN,NaN,2131164.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
20,AGE50-54,50-54 years,NaN,SRB,Serbia,NaN,NaN,23.400,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
21,AGE55-59,55-59 years,NaN,SRB,Serbia,NaN,NaN,0.016,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
22,AGE55-59,55-59 years,NaN,SRB,Serbia,NaN,NaN,0.079,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
23,AGE65-69,65-69 years,NaN,SRB,Serbia,NaN,NaN,0.189,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
24,AGE65-69,65-69 years,NaN,SRB,Serbia,NaN,NaN,70480.440,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
25,AGE65-69,65-69 years,NaN,SRB,Serbia,NaN,NaN,13332.160,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
26,AGE65-69,65-69 years,NaN,SRB,Serbia,NaN,NaN,320175.300,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
27,AGE75-79,75-79 years,NaN,SRB,Serbia,NaN,NaN,16319.910,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
28,AGE75-79,75-79 years,NaN,SRB,Serbia,NaN,NaN,170869.500,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
29,AGE75-79,75-79 years,NaN,SRB,Serbia,NaN,NaN,317775.400,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,MLE,Male,NaN,NaN,NaN,2000.0,2000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4492,AGE5-9,5-9 years,NaN,LVA,Latvia,NaN,NaN,0.000,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4493,AGE5-9,5-9 years,NaN,LVA,Latvia,NaN,NaN,7460043.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4494,AGE10-14,10-14 years,NaN,LVA,Latvia,NaN,NaN,0.000,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4495,AGE15-19,15-19 years,NaN,LVA,Latvia,NaN,NaN,0.000,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4496,AGE15-19,15-19 years,NaN,LVA,Latvia,NaN,NaN,99246.860,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4497,AGE20-24,20-24 years,NaN,LVA,Latvia,NaN,NaN,0.000,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4498,AGE20-24,20-24 years,NaN,LVA,Latvia,NaN,NaN,99150.520,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4499,AGE20-24,20-24 years,NaN,LVA,Latvia,NaN,NaN,495335.600,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4500,AGE25-29,25-29 years,NaN,LVA,Latvia,NaN,NaN,98973.300,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4501,AGE25-29,25-29 years,NaN,LVA,Latvia,NaN,NaN,494277.800,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4502,AGE30-34,30-34 years,NaN,LVA,Latvia,NaN,NaN,492648.800,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4503,AGE30-34,30-34 years,NaN,LVA,Latvia,NaN,NaN,50.500,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4504,AGE35-39,35-39 years,NaN,LVA,Latvia,NaN,NaN,45.700,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4505,AGE40-44,40-44 years,NaN,LVA,Latvia,NaN,NaN,0.010,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4506,AGE40-44,40-44 years,NaN,LVA,Latvia,NaN,NaN,40.900,LIFE_0000000035,ex - expectation of life at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4507,AGE45-49,45-49 years,NaN,LVA,Latvia,NaN,NaN,0.014,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4508,AGE50-54,50-54 years,NaN,LVA,Latvia,NaN,NaN,0.020,LIFE_0000000030,nqx - probability of dying between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4509,AGE50-54,50-54 years,NaN,LVA,Latvia,NaN,NaN,1876.525,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4510,AGE55-59,55-59 years,NaN,LVA,Latvia,NaN,NaN,2643.242,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4511,AGE55-59,55-59 years,NaN,LVA,Latvia,NaN,NaN,2558368.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4512,AGE60-64,60-64 years,NaN,LVA,Latvia,NaN,NaN,4020.501,LIFE_0000000032,ndx - number of people dying between ages x an...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4513,AGE60-64,60-64 years,NaN,LVA,Latvia,NaN,NaN,2096830.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4514,AGE65-69,65-69 years,NaN,LVA,Latvia,NaN,NaN,1651772.000,LIFE_0000000034,Tx - person-years lived above age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4515,AGE70-74,70-74 years,NaN,LVA,Latvia,NaN,NaN,0.022,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4516,AGE75-79,75-79 years,NaN,LVA,Latvia,NaN,NaN,0.035,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4517,AGE75-79,75-79 years,NaN,LVA,Latvia,NaN,NaN,72850.360,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4518,AGE80-84,80-84 years,NaN,LVA,Latvia,NaN,NaN,0.071,LIFE_0000000029,nMx - age-specific death rate between ages x a...,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4519,AGE80-84,80-84 years,NaN,LVA,Latvia,NaN,NaN,61088.540,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4520,AGE85PLUS,85+ years,NaN,LVA,Latvia,NaN,NaN,42526.780,LIFE_0000000031,lx - number of people left alive at age x,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN
4521,AGE85PLUS,85+ years,NaN,LVA,Latvia,NaN,NaN,245963.700,LIFE_0000000033,nLx - person-years lived between ages x and x+n,...,Europe,NaN,FMLE,Female,NaN,NaN,NaN,2016.0,2016.0,NaN

In [92]:
adf.columns

Index(['AGEGROUP (CODE)', 'AGEGROUP (DISPLAY)', 'AGEGROUP (URL)',
       'COUNTRY (CODE)', 'COUNTRY (DISPLAY)', 'COUNTRY (URL)', 'Comments',
       'Display Value', 'GHO (CODE)', 'GHO (DISPLAY)', 'GHO (URL)', 'High',
       'Low', 'Numeric', 'PUBLISHSTATE (CODE)', 'PUBLISHSTATE (DISPLAY)',
       'PUBLISHSTATE (URL)', 'REGION (CODE)', 'REGION (DISPLAY)',
       'REGION (URL)', 'SEX (CODE)', 'SEX (DISPLAY)', 'SEX (URL)', 'StdDev',
       'StdErr', 'YEAR (CODE)', 'YEAR (DISPLAY)', 'YEAR (URL)'],
      dtype='object')

In [99]:
adf.groupby(['COUNTRY (CODE)', 'YEAR (CODE)', 'SEX (CODE)', 'AGEGROUP (CODE)', 'GHO (DISPLAY)', 'Display Value']).size()

COUNTRY (CODE)  YEAR (CODE)  SEX (CODE)  AGEGROUP (CODE)  GHO (DISPLAY)                                         Display Value
AFG             2000.0       FMLE        AGE1-4           Tx - person-years lived above age x                   5637754.000      1
                                                          ex - expectation of life at age x                     61.600           1
                                                          lx - number of people left alive at age x             91527.040        1
                                                          nLx - person-years lived between ages x and x+n       356093.000       1
                                                          nMx - age-specific death rate between ages x and x+n  0.011            1
                                                          ndx - number of people dying between ages x and x+n   4018.467         1
                                                          nqx - probability of dying between ages x and x+n     0.044            1
                                         AGE10-14         Tx - person-years lived above age x                   4846139.000      1
                                                          ex - expectation of life at age x                     55.800           1
                                                          lx - number of people left alive at age x             86799.400        1
                                                          nLx - person-years lived between ages x and x+n       432426.400       1
                                                          nMx - age-specific death rate between ages x and x+n  0.001            1
                                                          ndx - number of people dying between ages x and x+n   633.477          1
                                                          nqx - probability of dying between ages x and x+n     0.007            1
                                         AGE15-19         Tx - person-years lived above age x                   4413712.000      1
                                                          ex - expectation of life at age x                     51.200           1
                                                          lx - number of people left alive at age x             86165.920        1
                                                          nLx - person-years lived between ages x and x+n       427477.900       1
                                                          nMx - age-specific death rate between ages x and x+n  0.003            1
                                                          ndx - number of people dying between ages x and x+n   1411.945         1
                                                          nqx - probability of dying between ages x and x+n     0.016            1
                                         AGE20-24         Tx - person-years lived above age x                   3986234.000      1
                                                          ex - expectation of life at age x                     47.000           1
                                                          lx - number of people left alive at age x             84753.980        1
                                                          nLx - person-years lived between ages x and x+n       419452.800       1
                                                          nMx - age-specific death rate between ages x and x+n  0.004            1
                                                          ndx - number of people dying between ages x and x+n   1780.335         1
                                                          nqx - probability of dying between ages x and x+n     0.021            1
                                         AGE25-29         Tx - person-years lived above age x                   3566781.000      1
                                                          ex - expectation of life at age x                     43.000           1
                                                                                                                                ..
ZWE             2016.0       MLE         AGE70-74         ndx - number of people dying between ages x and x+n   9874.203         1
                                                          nqx - probability of dying between ages x and x+n     0.231            1
                                         AGE75-79         Tx - person-years lived above age x                   266790.800       1
                                                          ex - expectation of life at age x                     8.100            1
                                                          lx - number of people left alive at age x             32809.900        1
                                                          nLx - person-years lived between ages x and x+n       136568.800       1
                                                          nMx - age-specific death rate between ages x and x+n  0.081            1
                                                          ndx - number of people dying between ages x and x+n   11091.890        1
                                                          nqx - probability of dying between ages x and x+n     0.338            1
                                         AGE80-84         Tx - person-years lived above age x                   130222.000       1
                                                          ex - expectation of life at age x                     6.000            1
                                                          lx - number of people left alive at age x             21718.010        1
                                                          nLx - person-years lived between ages x and x+n       81637.880        1
                                                          nMx - age-specific death rate between ages x and x+n  0.129            1
                                                          ndx - number of people dying between ages x and x+n   10527.030        1
                                                          nqx - probability of dying between ages x and x+n     0.485            1
                                         AGE85PLUS        Tx - person-years lived above age x                   48584.150        1
                                                          ex - expectation of life at age x                     4.300            1
                                                          lx - number of people left alive at age x             11190.980        1
                                                          nLx - person-years lived between ages x and x+n       48584.150        1
                                                          nMx - age-specific death rate between ages x and x+n  0.230            1
                                                          ndx - number of people dying between ages x and x+n   11190.980        1
                                                          nqx - probability of dying between ages x and x+n     1.000            1
                                         AGELT1           Tx - person-years lived above age x                   5962081.000      1
                                                          ex - expectation of life at age x                     59.600           1
                                                          lx - number of people left alive at age x             100000.000       1
                                                          nLx - person-years lived between ages x and x+n       96358.490        1
                                                          nMx - age-specific death rate between ages x and x+n  0.045            1
                                                          ndx - number of people dying between ages x and x+n   4379.245         1
                                                          nqx - probability of dying between ages x and x+n     0.044            1
Length: 820946, dtype: int64

In [102]:
adf[adf['COUNTRY (CODE)']=='CHN'].groupby(['YEAR (CODE)', 'SEX (CODE)', 'AGEGROUP (CODE)', 'GHO (DISPLAY)', 'Display Value']).size()

YEAR (CODE)  SEX (CODE)  AGEGROUP (CODE)  GHO (DISPLAY)                                         Display Value
2000.0       FMLE        AGE1-4           Tx - person-years lived above age x                   7268668.000      1
                                          ex - expectation of life at age x                     74.700           1
                                          lx - number of people left alive at age x             97261.570        1
                                          nLx - person-years lived between ages x and x+n       387206.700       1
                                          nMx - age-specific death rate between ages x and x+n  0.002            1
                                          ndx - number of people dying between ages x and x+n   729.553          1
                                          nqx - probability of dying between ages x and x+n     0.008            1
                         AGE10-14         Tx - person-years lived above age x                   6399413.000      1
                                          ex - expectation of life at age x                     66.500           1
                                          lx - number of people left alive at age x             96287.290        1
                                          nLx - person-years lived between ages x and x+n       481022.100       1
                                          nMx - age-specific death rate between ages x and x+n  0.000            1
                                          ndx - number of people dying between ages x and x+n   165.736          1
                                          nqx - probability of dying between ages x and x+n     0.002            1
                         AGE15-19         Tx - person-years lived above age x                   5918391.000      1
                                          ex - expectation of life at age x                     61.600           1
                                          lx - number of people left alive at age x             96121.550        1
                                          nLx - person-years lived between ages x and x+n       480012.800       1
                                          nMx - age-specific death rate between ages x and x+n  0.001            1
                                          ndx - number of people dying between ages x and x+n   251.868          1
                                          nqx - probability of dying between ages x and x+n     0.003            1
                         AGE20-24         Tx - person-years lived above age x                   5438379.000      1
                                          ex - expectation of life at age x                     56.700           1
                                          lx - number of people left alive at age x             95869.690        1
                                          nLx - person-years lived between ages x and x+n       478623.700       1
                                          nMx - age-specific death rate between ages x and x+n  0.001            1
                                          ndx - number of people dying between ages x and x+n   300.625          1
                                          nqx - probability of dying between ages x and x+n     0.003            1
                         AGE25-29         Tx - person-years lived above age x                   4959755.000      1
                                          ex - expectation of life at age x                     51.900           1
                                                                                                                ..
2016.0       MLE         AGE70-74         ndx - number of people dying between ages x and x+n   15062.440        1
                                          nqx - probability of dying between ages x and x+n     0.204            1
                         AGE75-79         Tx - person-years lived above age x                   515720.800       1
                                          ex - expectation of life at age x                     8.800            1
                                          lx - number of people left alive at age x             58769.880        1
                                          nLx - person-years lived between ages x and x+n       247251.400       1
                                          nMx - age-specific death rate between ages x and x+n  0.076            1
                                          ndx - number of people dying between ages x and x+n   18857.300        1
                                          nqx - probability of dying between ages x and x+n     0.321            1
                         AGE80-84         Tx - person-years lived above age x                   268469.400       1
                                          ex - expectation of life at age x                     6.700            1
                                          lx - number of people left alive at age x             39912.580        1
                                          nLx - person-years lived between ages x and x+n       155305.800       1
                                          nMx - age-specific death rate between ages x and x+n  0.111            1
                                          ndx - number of people dying between ages x and x+n   17259.960        1
                                          nqx - probability of dying between ages x and x+n     0.432            1
                         AGE85PLUS        Tx - person-years lived above age x                   113163.600       1
                                          ex - expectation of life at age x                     5.000            1
                                          lx - number of people left alive at age x             22652.620        1
                                          nLx - person-years lived between ages x and x+n       113163.600       1
                                          nMx - age-specific death rate between ages x and x+n  0.200            1
                                          ndx - number of people dying between ages x and x+n   22652.620        1
                                          nqx - probability of dying between ages x and x+n     1.000            1
                         AGELT1           Tx - person-years lived above age x                   7501072.000      1
                                          ex - expectation of life at age x                     75.000           1
                                          lx - number of people left alive at age x             100000.000       1
                                          nLx - person-years lived between ages x and x+n       99234.020        1
                                          nMx - age-specific death rate between ages x and x+n  0.008            1
                                          ndx - number of people dying between ages x and x+n   827.525          1
                                          nqx - probability of dying between ages x and x+n     0.008            1
Length: 4522, dtype: int64

In [104]:
adf.to_csv('who-lt.csv.gz', index=False)